name: 02 - Sent Tests to DA

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Test Project"]
    branches: [master]
    types:
      - completed
jobs:
  send_test_to_DA:
    
    runs-on: windows-latest
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.8
      - name: Display structure of downloaded files
        run: ls -R
