name: 02 - Read Results

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      
      - name: Download
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |
            Write-Host Downloading...
            $url = "https://developer.api.autodesk.com/oss/v2/signedresources/a83517ce-e219-44ba-8bcf-ffb35015e661?region=US"
            $response=Invoke-RestMethod $url
            $response.Save("result.xml")
            [xml]$xml = Get-Content result.xml
            $test_cases = $xml.SelectNodes("//test-case")
            Write-Host Reading results...
            Write-Host
            ForEach($case in $test_cases){
            	if ($case."result" -ne "Passed") {
            		Write-Host test case  : $case."fullname" -ForegroundColor red
            		Write-Host result     : $case."result" -ForegroundColor red
            		Write-Host
            	} else {
            		Write-Host test case  : $case."fullname" -ForegroundColor green
            		Write-Host result     : $case."result" -ForegroundColor green
            		Write-Host
            	}
            }
            
            if ($err -eq 1) {
            	throw "ONE OR MORE TEST FAILED! Please check test cases above."
            } else {
            	Write-Host All test passed! -ForegroundColor green
            }
