name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Test Script
        run: |
          dir
      - name: Download
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |
            Write-Host Downloading...
            $url = "https://developer.api.autodesk.com/oss/v2/signedresources/13e7ef86-3351-4971-8fae-9be9ac366046?region=US"
            $response = Invoke-RestMethod $url -Method 'GET' -Headers $headers | Out-File results.xml
      - name: Test Script
        run: |
          dir
