name: 02 - Read Results

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      
      - name: Download
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |
            Write-Host Downloading...
            $url = "https://developer.api.autodesk.com/oss/v2/signedresources/a83517ce-e219-44ba-8bcf-ffb35015e661?region=US"
            $response=Invoke-RestMethod $url
            $response.Save("result.xml")
            [xml]$xml = Get-Content result.xml
            $test_cases = $xml.SelectNodes("//test-case")
            $color = [console]::ForegroundColor
            $err = 0
            ForEach($case in $test_cases){
            	if ($case."result" -ne "Passed") {
            		[console]::ForegroundColor="red"; $_;
            		$err = 1
            		$case
            	} else {
            		[console]::ForegroundColor="green"; $_;
            		$case
            	}
            }
            
            if ($err -eq 1) {
            	[console]::ForegroundColor="red"; $_;
            	throw "ONE OR MORE TEST FAILED!"
            }
            
            [console]::ForegroundColor = $color 
            Write-Host Finished Test Report
