name: 02 - Test Results
 
on:
  workflow_dispatch:

jobs:
  test_results:
    runs-on: windows-latest
    steps:
      - name: Post
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script: |
            $WebClient = New-Object System.Net.WebClient
            $WebClient.DownloadFile("https://developer.api.autodesk.com/oss/v2/signedresources/342a4135-07d2-4e8b-8283-4a61dd6472bb?region=US","result.xml")
            Get-Content -Path result.xml
